trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    cd infra
    terraform init
    terraform plan
    terraform apply -auto-approve
  displayName: 'Run a multi-line script'